name: CI Tests
on: [pull_request]
jobs:
  test_seurat_io:
    name: Test Seurat 4 IO
    runs-on: ubuntu-latest
    steps:
      - name: Setup BATS
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.2.1
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: test-wsc-seurat-4
          python-version: 3.8
          environment-file: test_environment.yml
          channels: defaults,conda-forge,bioconda
          auto-activate-base: false
          mamba-version: "*"
      - name: Tests
        shell: bash -l {0}
        run: |
          R -e 'remotes::install_github("satijalab/seurat-data", dependencies=FALSE)'
          conda list
          conda info
          bash ./run_tests.sh
          
